src/App.tsx
src/pages/Test.tsx

etc: 걍 만지작 거려봄

---

src/components/Poster.tsx
src/components/Result.tsx
src/components/Search.tsx
src/components/Tags.tsx
src/pages/Home.tsx
src/pages/SearchPage.tsx
src/store.tsx

etc: searchpage 수정중

---

src/components/Result.tsx
src/pages/SearchPage.tsx
src/store.tsx

feat: Search 기능 완성

---

src/components/Poster.tsx
src/components/Result.tsx
src/components/Search.tsx
src/components/Tags.tsx
src/pages/SearchPage.tsx
src/store.tsx

- 
<br />
- 배열을 검색할 때 array.toString()으로 문자열로 치환한 뒤 검색할 수 있다
<br />
-

feat: Search ->cast검색 추가, design: SearchPage 위치 잡기

---

src/components/tabContent.tsx

- 12
<br />
- 파라미터값이 존재하지 않는 페이지는 (가령 :id 값이 234이면) 화면을 안 보내줄 거임.
- 리턴에 조건문을 달아줬음!!
<br />
- 근데 맞게 하는 건지 모르겠네유 ㅎ

깨진 페이지 vs 빈 페이지(혹은 404로 안내해도 될듯)

---

src/components/tabContent.tsx

- 
<br />
- 파라미터값이 없는 페이지는 다르게 처리하는 게 맞다 싶었음
- 가령 :id값이 234인 경우 -> 데이터가 없어서 깨진 화면보단 빈페이지, 혹은 404 페이지를 보내주는 게 낫다
- JSX 리턴값에 조건문을 달아줌
<br />
- 맞아..?

feat: JSX return 조건 추가

---

src/components/Poster.tsx
src/components/Result.tsx
src/components/Search.tsx
src/components/Tags.tsx
src/components/index.ts
src/pages/SearchPage.tsx
src/pages/index.ts
src/store.tsx
src/styles/globalStyle.ts

feat: Search 개선, design: scrollbar제거 searchpage 반응형추가

---

package.json
src/components/MovieSlide.tsx
src/components/index.ts
src/pages/Home.tsx
src/styles/globalStyle.ts
yarn.lock

feat: carousel init point

---

src/App.tsx
src/components/TabContent.tsx
src/components/TabTitle.tsx
src/components/index.ts
src/pages/Detail.tsx
src/pages/index.ts

- div로 선 그으라는 꿀팁이 주효했어요
<br />
- 참고한 링크는 없고. props를 이용한 동적인 스타일링의 편함을 느껴벌임ㅎ  🎉
<br />
-

탭: 슬라이딩 언더라인 추가

---

src/components/MovieSlide.tsx
src/components/Poster.tsx
src/pages/Home.tsx

feat: poster 기울임 이벤트

---

src/components/DataDummy.tsx
src/components/MovieSlide.tsx
src/components/Poster.tsx

fix: ts error fix

---

src/components/MovieSlide.tsx
src/pages/Home.tsx
src/styles/globalStyle.ts

feat : 스크롤이벤트 추가

---

src/components/MovieSlide.tsx

design : 슬라이더수정

---

src/pages/Home.tsx

etc: refactoring 중 버그 발생

---

src/components/Search.tsx
src/components/TabContent.tsx
src/components/TabTitle.tsx

fix: 탭, 서치바 디자인 버그 픽스

---

src/components/MovieSlide.tsx
src/pages/Home.tsx
src/store.tsx

- 
<br />
- state를 useEffect의 의존성에 등록해야 변화된 값을 들고 올 수 있다
<br />
-

fix: scroll 반응형 수정

---

src/components/MovieSlide.tsx
src/components/Result.tsx
src/pages/Home.tsx

feat: Home footer, design: result mobile, movieSlide design

---

src/components/MovieSlide.tsx
src/pages/Home.tsx
src/store.tsx

refactor: Home scroll event useState->redux

---

src/components/MovieSlide.tsx
src/components/Poster.tsx
src/components/Result.tsx
src/components/Tags.tsx
src/pages/Home.tsx
src/pages/SearchPage.tsx
src/store.tsx

feat: movieslide 반응형, design: poster 반응형 규격 수정

---

src/components/Canvas/Canvas.tsx
src/pages/Home.tsx

feat : canvas animation

---

src/components/Footer.tsx
src/components/MovieSlide.tsx
src/components/Search/SearchForm.tsx
src/components/Search/SearchResult.tsx
src/components/Search/Tags.tsx
src/components/TabTitle.tsx
src/components/TeamComment.tsx
src/components/TempTest/TempQna/AnswerList.tsx
src/pages/Home.tsx
src/pages/SearchPage.tsx
src/store.tsx
src/styles/globalStyle.ts

design: 전체 theme color 변경

---

src/components/Canvas/Canvas.tsx
src/components/Character/Character.tsx
src/pages/TestResultPage.tsx

feat : 캐릭터슬라이드 슬릭추가

---

src/components/Canvas/Canvas.tsx
src/components/Layout.tsx

design: canavas, navbar 디자인 추가

---

src/components/Home/Character.tsx
src/components/Home/TeamComment.tsx
src/components/Search/Tags.tsx

design : 버튼 디자인변경

---

src/components/Main/Footer.tsx
src/pages/Home.tsx
src/store.tsx

design: footer 수정

---

src/components/Test/Qna/AnswerList.tsx
src/pages/TestResultPage.tsx

feat: test result를 불러오는 상황에만 loading되게 변경

---

src/components/Home/TeamComment.tsx

design: comment 말풍선

---

src/components/Home/Canvas.tsx
src/components/Main/Footer.tsx
src/components/Search/SearchForm.tsx
src/components/Test/Result/Loading.tsx
src/pages/TestResultPage.tsx
src/styles/globalStyle.ts

design: 메인폰트 변경(글로벌스타일 body에 적용, 여기어때잘난체)

---

src/components/Search/Tags.tsx
src/store.tsx

feat: Tag 중복선택, selectedTag

---

src/components/Home/TeamComment.tsx

design : 코멘트수정

---

src/components/Home/Character.tsx
src/components/Home/MovieSlide.tsx
src/components/Main/Layout.tsx
src/components/Search/Tags.tsx
src/pages/TestPage.tsx
src/styles/globalStyle.ts

design: body 컬러 통일

---

src/components/Home/Canvas.tsx
src/components/Main/DataLoad.tsx
src/pages/Home.tsx
src/store.tsx

feat. 홈 애니메이션 수정

---

src/components/Home/MovieSlide.tsx
src/components/Main/DataLoad.tsx

feat: movieList shuffle

---

src/components/Home/Canvas.tsx
src/components/Home/Character.tsx

feat. 캐릭터슬라이드 애니메이션추가

---

package.json
src/components/Detail/TabContent.tsx
src/components/Detail/TabTitle.tsx
src/components/Main/DataLoad.tsx
src/components/Test/Result/TestResult.tsx
src/pages/Detail.tsx
src/pages/TestPage.tsx
yarn.lock

feat: 네이버영화 크롤링, 공유하기 버튼

---

src/components/Home/TeamComment.tsx
src/components/Main/DataLoad.tsx
src/store.tsx

refactor: 코멘트위치변경
